# Generated by Django 3.2.10 on 2022-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('organisationNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
