# Generated by Django 3.2.10 on 2022-03-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('productUrl', models.URLField(blank=True, null=True)),
                ('imageUrl', models.URLField()),
                ('organisationProductID', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('slug', models.SlugField(unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(max_length=100, unique=True)),
                ('userDetails', models.JSONField()),
                ('currentAmount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
